### ISSUE TITLE
!simpsons

### ISSUE THREAD

**Issue by BradWells** [Joelpls/discord-bot#13]
!simpsons bart chalkboard

Expected behavior, posting the top left picture of a search for "bart chalkboard" on https://frinkiac.com/

Implementation example:
Use beautifulsoup to hit https://frinkiac.com/ and get all img tags
Get first one and copy it's href link
Send message to discord with the href link

**Comment by iantrich** [comment]
About time

**Comment by Joelpls** [comment]
complete
